# 2.2 数据操作

In [34]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.2.0


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [39]:
x = torch.empty(5, 3)
print(x)

tensor([[9.1837e-39, 8.4490e-39, 9.2755e-39],
        [1.0469e-38, 8.4490e-39, 9.2756e-39],
        [1.0837e-38, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39]])


创建一个5x3的随机初始化的`Tensor`:



In [36]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


创建一个5x3的long型全0的`Tensor`:



In [40]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [41]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [46]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2375, -0.7723, -1.2006],
        [-0.3354, -0.1143, -0.4537],
        [ 2.3055, -0.3790, -0.4669],
        [-0.4609,  1.2652,  1.5746],
        [-0.5010,  0.4818, -0.3123]])


我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [54]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

## 2.2.2 操作
### 算术操作
* **加法形式一**

In [55]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9415,  0.1792, -0.5196],
        [-0.2867,  0.7020, -0.0114],
        [ 2.5823,  0.5208, -0.3710],
        [ 0.0928,  1.6605,  2.4316],
        [ 0.1385,  1.2221,  0.3643]])


* **加法形式二**

In [56]:
print(torch.add(x, y))

tensor([[-0.9415,  0.1792, -0.5196],
        [-0.2867,  0.7020, -0.0114],
        [ 2.5823,  0.5208, -0.3710],
        [ 0.0928,  1.6605,  2.4316],
        [ 0.1385,  1.2221,  0.3643]])


In [57]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9415,  0.1792, -0.5196],
        [-0.2867,  0.7020, -0.0114],
        [ 2.5823,  0.5208, -0.3710],
        [ 0.0928,  1.6605,  2.4316],
        [ 0.1385,  1.2221,  0.3643]])


* **加法形式三、inplace**

In [58]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.9415,  0.1792, -0.5196],
        [-0.2867,  0.7020, -0.0114],
        [ 2.5823,  0.5208, -0.3710],
        [ 0.0928,  1.6605,  2.4316],
        [ 0.1385,  1.2221,  0.3643]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [59]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([-0.2375,  0.2277, -0.2006])
tensor([-0.2375,  0.2277, -0.2006])


### 改变形状
用`view()`来改变`Tensor`的形状：

In [64]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

tensor([[-0.2375,  0.2277, -0.2006],
        [-0.3354, -0.1143, -0.4537],
        [ 2.3055, -0.3790, -0.4669],
        [-0.4609,  1.2652,  1.5746],
        [-0.5010,  0.4818, -0.3123]]) tensor([-0.2375,  0.2277, -0.2006, -0.3354, -0.1143, -0.4537,  2.3055, -0.3790,
        -0.4669, -0.4609,  1.2652,  1.5746, -0.5010,  0.4818, -0.3123]) tensor([[-0.2375,  0.2277, -0.2006, -0.3354, -0.1143],
        [-0.4537,  2.3055, -0.3790, -0.4669, -0.4609],
        [ 1.2652,  1.5746, -0.5010,  0.4818, -0.3123]])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [65]:
x += 1
print(x)
print(y) # 也加了1

tensor([[0.7625, 1.2277, 0.7994],
        [0.6646, 0.8857, 0.5463],
        [3.3055, 0.6210, 0.5331],
        [0.5391, 2.2652, 2.5746],
        [0.4990, 1.4818, 0.6877]])
tensor([0.7625, 1.2277, 0.7994, 0.6646, 0.8857, 0.5463, 3.3055, 0.6210, 0.5331,
        0.5391, 2.2652, 2.5746, 0.4990, 1.4818, 0.6877])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [15]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.6035,  1.8110,  0.9549],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])
tensor([2.6035, 2.8110, 1.9549, 1.8797, 2.0482, 0.9555, 0.2771, 3.8663, 0.4345,
        1.1604, 0.9746, 2.0739, 3.2628, 0.0825, 0.7749])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.3466])
2.3466382026672363


## 2.2.3 广播机制

In [17]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 运算的内存开销

In [18]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [19]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [20]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变！！！**
### `Tensor`转NumPy

In [21]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [23]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [5]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型